ss4o-cloudtrail-pipeline:
  source:
    http:
  processor:
    - parse_json:
        source: "message"
        destination: "parsed"
    - rename_keys:
        entries:
          - from_key: "parsed"
            to_key: "aws/cloudtrail"
          - from_key: "message"
            to_key: "body"
          - from_key: "timestamp"
            to_key: "observedTimestamp"
          - from_key: "logGroup"
            to_key: "event/log_group"
          - from_key: "logStream"
            to_key: "event/log_stream"
          - from_key: "owner"
            to_key: "cloud/account/id"
    - copy_values:
        entries:
          - from_key: "aws/cloudtrail/eventTime"
            to_key: "@timestamp"
          - from_key: "aws/cloudtrail/eventId"
            to_key: "traceId"
          - from_key: "aws/cloudtrail/awsRegion"
            to_key: "cloud/region"
          - from_key: "aws/cloudtrail/cloud/account/name"
            to_key: "cloud/account/name"
          - from_key: "aws/cloudtrail/eventSource"
            to_key: "cloud/service/name"
    - add_entries:
        entries:
          # https://github.com/opensearch-project/opensearch-catalog/tree/main/docs/schema/observability/logs
          - key: "attributes/data_stream/dataset"
            value: "cloudtrail_log"
          - key: "attributes/data_stream/namespace"
            value: "production"
          - key: "attributes/data_stream/type"
            value: "cloud_trail_logs"
          - key: "event/domain"
            value: "cloudtrail"
          - key: "event/source"
            value: "cloudwatch"
          - key: "event/name"
            value: "cloud_trail"
          - key: "event/result"
            value:  "accept"
          - key: "event/kind"
            value: "event"
          - key: "event/category"
            value: "iam"
          - key: "cloud/provider"
            value: "aws"
          - key: "event/type"
            value: "access"
    - delete_entries:
        with_keys: ["parsed"]
          # TODO: How to identify an ARN consistently???
          # - from_key: "parsed/cloud/resource_id"
          #   to_key: "cloud/resource_id"
  sink:
    - opensearch:
        hosts: ["https://vpc-os-zwy2-us-gov-west-1-demo-mnfhpkqgmzrlgwkqh2kulkfnqy.us-gov-west-1.es.amazonaws.com"]
        aws_sigv4: true
        index_type: custom
        index: ss4o_logs-aws_cloudtrail-production
        aws_region: "us-gov-west-1"